services:
    _defaults:
        autoconfigure: true

    contao_image_alternatives.image.picture_factory:
        class: InspiredMinds\ContaoImageAlternatives\Image\PictureFactory
        decorates: contao.image.picture_factory
        arguments:
            - '@contao_image_alternatives.image.picture_factory.inner'
            - '@contao.image.factory'
            - '@contao.image.resizer'
            - '%contao_image_alternatives.alternative_sizes%'
            - '%contao_image_alternatives.predefined_sizes%'
            - '%kernel.project_dir%'

    contao_image_alternatives.data_container.image_alternatives:
        class: InspiredMinds\ContaoImageAlternatives\EventListener\DataContainer\ImageAlternativesListener
        arguments:
            - '@request_stack'
            - '@translator'
            - '%contao_image_alternatives.alternatives%'
            - '%kernel.project_dir%'
            - '%contao.image.valid_extensions%'

    contao_image_alternatives.data_container.important_parts:
        class: InspiredMinds\ContaoImageAlternatives\EventListener\DataContainer\ImportantPartsListener
        arguments:
            - '@request_stack'
            - '%kernel.project_dir%'
            - '%contao.image.valid_extensions%'

    InspiredMinds\ContaoImageAlternatives\EventListener\AddBackendAssetsListener:
        autowire: true
