services:
    contao_image_alternatives.image.picture_factory:
        class: InspiredMinds\ContaoImageAlternatives\Image\PictureFactory
        decorates: contao.image.picture_factory
        arguments:
            - '@contao_image_alternatives.image.picture_factory.inner'
            - '%contao_image_alternatives.alternative_sizes%'
            - '%contao_image_alternatives.predefined_sizes%'
            - '%kernel.project_dir%'

    contao_image_alternatives.data_container.image_alternatives:
        class: InspiredMinds\ContaoImageAlternatives\EventListener\DataContainer\ImageAlternativesListener
        arguments:
            - '@request_stack'
            - '@translator'
            - '%contao_image_alternatives.alternatives%'
            - '%kernel.project_dir%'
        tags:
            - { name: contao.callback, table: tl_files, target: config.onload, method: adjustDataContainer }
